import Navbar from "@/components/Navbar"
import { Ubuntu } from "@next/font/google"
import "./globals.css"

export const metadata = {
  title: "GLDGN Portfolio",
  description: "Generated by create next app",
}

const roboto = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "700"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-5/6 m-auto">
      <body className={`bg-primary ${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
